### ISSUE TITLE
Julia Binary Classifier plot colors 

### ISSUE THREAD

**Issue by caxelrud** [oxinabox/oxinabox.github.io#6]
I run the notebook and it show different colors in the plots that make them difficult to visualize. It shows white to black dots and not the blue shades you have in your post.
I am using a Windows OS. 
I run the same code in VSCode with the same results.
Any recommendations?

**Comment by caxelrud** [comment]
Running without pyplot() works well.

**Comment by oxinabox** [comment]
Fair enough, it is a rather aged post, and the various libraries, including plotting have changed.
